### ISSUE TITLE
Getting errors when running the unit test

### ISSUE THREAD

**Issue by Cruiseee** [hakyimlab/ukbrest#1] opened 2019-08-07 10:46 UTC
Hi,
Thanks for making ukbrest tool. I need help in the installation of the ukbrest in the server. I'm getting some errors (see attached screenshot) in the when running the unit test using the command "python -m unittest discover". I also exported the bgenix path, but still i'm getting path/not/found for bgenix. How can I solve these errors? or can I ignore them?

![ukbrest_errors](https://user-images.githubusercontent.com/36948814/62616972-6a9fc300-b92e-11e9-81aa-94d1c77b4015.png)

Regards.

**Comment by miltondp** [comment] 2019-08-08 14:45
Hi Cruiseee, could you please provide the steps to reproduce this?

**Comment by miltondp** [comment] 2019-08-08 14:47
Hi Cruiseee, thanks for using the tool and report this problem.
Could you please provide the steps to reproduce this?

You can always take a look at the TravisCI script to see how we've setup up the continuous integration machine: https://github.com/hakyimlab/ukbrest/blob/master/.travis.yml

Thanks

**Comment by Cruiseee** [comment] 2019-08-12 04:46
Hi Milton, 
I just followed steps in the link [https://github.com/hakyimlab/ukbrest/wiki/Running-unit-tests]. I got the errors when I ran the command "python -m unittest discover". Prior to running this command, I exported the path of the bgenix using export PATH=$PATH:/path/to/bgenix. Even though after exporting the path of bgenix I'm getting error "path/not/found/bgenix" (as you can see in previously attached screenshot). So how can I avoid this error?

I hope this is clear. 
Thanks for the quick reply.

**Comment by miltondp** [comment] 2019-08-12 05:45
Hi Cruiseee,

I ran the unit tests again following that link and found that qctool was missing as a dependency (only used for unit tests). Other than that, everything worked correctly (all unit tests passed). I did this with a clean installation (a new conda environment, bgenix installed from scratch, as well as docker, psql, and qctool) and it worked in Ubuntu 18.04.

Please, note that you don't need to run the unit tests to get ukbREST working. This is only needed if, for some reason, you want to install it from scratch. You can just follow the instructions in the main page (https://github.com/hakyimlab/ukbrest) to use it through the Docker image, which is already tested and really the recommended way to go.

If you do want to run the tests, please, check that all dependencies (Docker, psql, qctool, bgenix, etc) are correctly installed. For instance, check that you can run `bgenix` and the path is the correct one.

**Comment by Cruiseee** [comment] 2019-08-14 10:36
Hi Milton,

Thanks for heads up on the qctool and after exporting it, I got few ERRORS. I have checked the path of the bgenix and it is working, but still, I'm getting error "path/not/found/bgenix". Anyways, I followed your recommendation (i.e., to use docker), it worked great on my local machine. Now I'll check it on the server. Once it is done, I'll update this comment.

One small question: Are you planning to develop web UI in the future? 

Thanks for your help.

**Comment by miltondp** [comment] 2019-08-15 14:25
Hi Cruiseee,

I'm glad you could install it. Yes, please, update this issue after you try it in the server.

I don't have plans to develop a web UI in the near feature, but could be a nice addition.

Thank you for using ukbREST and reporting this issue.

**Comment by miltondp** [comment] 2019-08-24 15:24
Closing this issue, since it's related to unit tests.

**Closed by miltondp** 2019-08-24 15:24 UTC

**Comment by Cruiseee** [comment] 2019-08-26 10:59
**Update:**

I have installed on the server and even though a few unit tests were failed ukbREST is working good. Thanks for your help.
